server:
   port: 9578

logging:
    path: logs
    file: bi.log


spring:
   application:
          name: bi
   datasource:
<<<<<<< Updated upstream
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://10.152.9.32:3306/test2?autoReconnect=true
       username: root
       password: qa@test
=======
       driver-class-name: oracle.jdbc.driver.OracleDriver
       url: jdbc:oracle:thin:@//101.201.239.70:1521/orcl
       username: hyf
       password: hyf123
>>>>>>> Stashed changes


mybatis:
    type-aliases-package: com.business.intelligence.model
    mapper-locations:
       - mapper/*

imgPath: /Users/wangfukun/other/img/
csvPath: /Users/wangfukun/other/img/




